package com.hongwei.model.arcgis.covid19

data class Attributes (
    var Date: Long,
    var NSW: Long,
    var VIC: Long,
    var QLD: Long,
    var SA: Long,
    var WA: Long,
    var TAS: Long,
    var NT: Long,
    var ACT: Long,
    var ObjectId: Long,
    var Total_Cases: Long,
    var NSW_Deaths: Long,
    var VIC_Deaths: Long,
    var QLD_Deaths: Long,
    var SA_Deaths: Long,
    var WA_Deaths: Long,
    var TAS_Deaths: Long,
    var NT_Deaths: Long,
    var ACT_Deaths: Long,
    var Total_Deaths: Long,
    var NSW_Tests: Long,
    var VIC_Tests: Long,
    var QLD_Tests: Long,
    var SA_Tests: Long,
    var WA_Tests: Long,
    var TAS_Tests: Long,
    var NT_Tests: Long,
    var ACT_Tests: Long,
    var NSW_Tests_Negative: Long,
    var VIC_Tests_Negative: Long,
    var QLD_Tests_Negative: Long,
    var SA_Tests_Negative: Long,
    var WA_Tests_Negative: Long,
    var TAS_Tests_Negative: Long,
    var NT_Tests_Negative: Long,
    var ACT_Tests_Negative: Long,
    var Total_Tests: Long,
    var Total_Tests_Negative: Long
)