package com.hongwei.model.arcgis.covid19;

public class Attributes {
    public Long Date;
    public Long NSW;
    public Long VIC;
    public Long QLD;
    public Long SA;
    public Long WA;
    public Long TAS;
    public Long NT;
    public Long ACT;
    public Long ObjectId;
    public Long Total_Cases;
    public Long NSW_Deaths;
    public Long VIC_Deaths;
    public Long QLD_Deaths;
    public Long SA_Deaths;
    public Long WA_Deaths;
    public Long TAS_Deaths;
    public Long NT_Deaths;
    public Long ACT_Deaths;
    public Long Total_Deaths;
    public Long NSW_Tests;
    public Long VIC_Tests;
    public Long QLD_Tests;
    public Long SA_Tests;
    public Long WA_Tests;
    public Long TAS_Tests;
    public Long NT_Tests;
    public Long ACT_Tests;
    public Long NSW_Tests_Negative;
    public Long VIC_Tests_Negative;
    public Long QLD_Tests_Negative;
    public Long SA_Tests_Negative;
    public Long WA_Tests_Negative;
    public Long TAS_Tests_Negative;
    public Long NT_Tests_Negative;
    public Long ACT_Tests_Negative;
    public Long Total_Tests;
    public Long Total_Tests_Negative;
}
