logging:
  file: "logs/config/mike_springboot2.log"
info:
  name: "springboot2"

server:
  port: 8082

#Td123456#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Td123456#
    driverClassName: com.mysql.jdbc.Driver

jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto : update

